servers:
  - id: alfa
    port: 5555
    url: localhost
    rabbitmq:
      exchange: alfa_exchange
      type: direct
      queue: alfa_queue
      connectionUrl: amqp://localhost
      callback_queue: anonymous
  - id: beta
    port: 4444
    url: localhost
    rabbitmq:
      exchange: beta_exchange
      type: topic
      queue: beta_queue
      connectionUrl: amqp://localhost
      callback_queue: beta_function
  - id: gama
    port: 3333
    url: localhost
    rabbitmq:
      exchange: gama_exchange
      type: rpc
      queue: gama_queue
      connectionUrl: amqp://localhost
      callback_queue: callback_gamma

functions:
  - name: funcao1
    server: alfa
    parameters:
      - name: a
        type: number
    method: rabbit
  - name: funcao2
    server: beta
    parameters:
      - name: a
        type: number
    method: rabbit
  - name: funcao3
    server: gama
    parameters:
      - name: a
        type: number
    method: rabbit
  - name: funcao4
    server: alfa
    parameters:
      - name: a
        type: number
    method: rabbit
  - name: funcao5
    server: beta
    parameters:
      - name: a
        type: number
    method: rabbit